### ISSUE TITLE
blackhole.io domain has expired

### ISSUE THREAD

**Issue by sruon** [kura/blackhole#3]
Hey,

Tried to access the documentation today and it appears the domain is no longer registered and is currently in the grace period. Any plans to restore it? 

Thanks !

**Comment by jadatkins** [comment]
@kura The domain is due to expire on Monday. Is everything alright?

(Also, what is your preferred pronoun?)

**Comment by jadatkins** [comment]
@kura Somebody has bought a backorder from nic.io. This means that they are guaranteed to receive control of the domain on Friday 18 September (two weeks from today) unless it is renewed before that time.

**Comment by jadatkins** [comment]
I have sent an email to nic.io asking if there is anything we can do if @kura is unreachable.  I doubt anything will come of it, though.

**Comment by sruon** [comment]
Domain is back

**Comment by jadatkins** [comment]
Er, yes, it is. I renewed it at the last minute. Apparently you don't need to be the domain owner to do that.
