### ISSUE TITLE
EHLO advertizing starttls without ssl options enabled

### ISSUE THREAD

**Issue by Tylerlhess** [kura/blackhole#4]
Need logic around the EHLO statements to only include options for starttls if SSL is enabled.

in data.py

EHLO_RESPONSES = ["250-OK", "250-SIZE {0}",
                  "250-VRFY", "250-STARTTLS",
                  "250-ENHANCEDSTATUSCODES", "250-8BITMIME",
                  "250 DSN"]

change to 

EHLO_RESPONSES = ["250-OK", "250-SIZE {0}",
                  "250-VRFY", "250-ENHANCEDSTATUSCODES", 
                  "250-8BITMIME", "250 DSN"]

if options.ssl or ssl:
                  EHLO_RESPONSES.append("250-STARTTLS")

Similar options can and should be appended based on the configurations

**Comment by kura** [comment]
Thanks. Will look in to that. Sorry, didn't notice the issue.

**Comment by kura** [comment]
The branch referenced above has a fix for STARTTLS referencing in EHLO. The branch is stable and working, tests are not though.

**Comment by kura** [comment]
This is now fixed and in master.
